version: '3.7'
services:

    php-fpm:
        image: ${REGISTRY}/${PHP_FMP_CONTAINER_NAME}:${IMAGE_TAG}
        volumes:
            - .:/var/www/html
        env_file: .env

    php-cli:
        image: ${REGISTRY}/${PHP_CLI_CONTAINER_NAME}:${IMAGE_TAG}
        volumes:
            - .:/app
        env_file: .env

    nginx:
        image: ${REGISTRY}/${NGINX_CONTAINER_NAME}:${IMAGE_TAG}
        ports:
            - ${APP_WEB_PORT}:80
        volumes:
            - .:/var/www/html

    mariadb:
        image: mariadb:10.4.10
        restart: "unless-stopped"
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - mariadb-storage:/var/lib/mysql
        env_file: .env


volumes:
    mariadb-storage:
